{"kind":"symbol","identifier":{"url":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultValue","kind":"identifier"}],"title":"ResultValue","externalID":"s:12TrustlessSDK11ResultValuea","modules":[{"name":"TrustlessSDK"}],"roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"ResultValue"}]},"sections":[],"abstract":[{"type":"text","text":"A typealias for the "},{"code":"Result","type":"codeVoice"},{"type":"text","text":" type specialized for the TrustlessSDK, where failures are represented by "},{"type":"codeVoice","code":"TrustlessError"},{"type":"text","text":"."}],"seeAlsoSections":[{"generated":true,"title":"Request and Response","identifiers":["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback"]}],"variants":[{"paths":["\/documentation\/trustlesssdk\/resultvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ResultValue","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Value","kind":"genericParameter"},{"text":"> = ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:12TrustlessSDK11ResultValuea0D0xmfp"},{"kind":"text","text":", "},{"text":"TrustlessError","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError","kind":"typeIdentifier","preciseIdentifier":"s:12TrustlessSDK0A5ErrorO"},{"text":">","kind":"text"}]}]},{"parameters":[{"name":"Value","content":[{"inlineContent":[{"text":"The type of the value in the success case.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"This type simplifies the handling of operations that can either succeed with a value of type ","type":"text"},{"type":"codeVoice","code":"Value"},{"text":" or fail with a ","type":"text"},{"code":"TrustlessError","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"It is used extensively across the SDK in functions that perform asynchronous tasks, such as network requests, which can either produce a result or an error."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK":{"role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK","type":"topic","title":"TrustlessSDK","url":"\/documentation\/trustlesssdk"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/TrustlessError":{"role":"symbol","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError","kind":"symbol","navigatorTitle":[{"text":"TrustlessError","kind":"identifier"}],"title":"TrustlessError","url":"\/documentation\/trustlesssdk\/trustlesserror","abstract":[{"text":"Describes errors that can occur within the TrustlessSDK.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TrustlessError","kind":"identifier"}],"type":"topic"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultValue":{"navigatorTitle":[{"text":"ResultValue","kind":"identifier"}],"url":"\/documentation\/trustlesssdk\/resultvalue","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A typealias for the "},{"type":"codeVoice","code":"Result"},{"type":"text","text":" type specialized for the TrustlessSDK, where failures are represented by "},{"code":"TrustlessError","type":"codeVoice"},{"text":".","type":"text"}],"title":"ResultValue","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultValue"}],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","type":"topic"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/CancelCallback":{"url":"\/documentation\/trustlesssdk\/cancelcallback","type":"topic","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CancelCallback"}],"navigatorTitle":[{"text":"CancelCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"A typealias for a closure used to cancel an ongoing operation."}],"title":"CancelCallback","kind":"symbol"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultCallback":{"url":"\/documentation\/trustlesssdk\/resultcallback","type":"topic","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ResultCallback","kind":"identifier"}],"navigatorTitle":[{"text":"ResultCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"A typealias for a callback function that is invoked with a "},{"code":"ResultValue","type":"codeVoice"},{"type":"text","text":"."}],"title":"ResultCallback","kind":"symbol"}}}